name: Playwright Tests
on:
  push:
    branches: [ main, master, dev, feature/arthur/automate-testing ]
  pull_request:
    branches: [ main, master, dev, feature/arthur/automate-testing ]

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js (with cache)
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'
          cache-dependency-path: ./frontend/package-lock.json
      
      - name: Install dependencies
        run: npm install
        working-directory: ./frontend

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install Python dependencies
        run: pip install -r requirements.txt
        working-directory: ./

      - uses: actions/cache@v4
        with:
          path: ~/.cache/ms-playwright
          key: ${{ runner.os }}-playwright-${{ hashFiles('frontend/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-playwright-

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
        working-directory: ./frontend

      - name: Run Playwright tests
        run: npx playwright test
        working-directory: ./frontend

      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: frontend/playwright-report/
          retention-days: 30

      - name: Install Docker
        run: |
          sudo apt-get update
          sudo apt-get install -y docker.io

      - name: Install gVisor
        run: |
          wget https://storage.googleapis.com/gvisor/releases/release/latest/x86_64/runsc
          chmod +x runsc
          sudo mv runsc /usr/local/bin/
          sudo runsc install

      - name: Configure Docker to use gVisor
        run: |
          echo '{"runtimes": {"runsc": {"path": "/usr/local/bin/runsc"}}}' | sudo tee /etc/docker/daemon.json
          sudo systemctl restart docker

      - name: Start Docker service
        run: sudo systemctl start docker

      - name: Verify Docker and gVisor setup
        run: |
          docker info
          docker run --runtime=runsc --rm hello-world
