name: Run Vitest Tests

on:
  push:
    branches:
      - main, 
      - dev, 
      - feature/arthur/automate-testing
  pull_request:
    branches:
      - main, 
      - dev, 
      - feature/arthur/automate-testing

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js (with cache)
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'
          cache-dependency-path: ./frontend/package-lock.json
      
      - name: Install dependencies
        run: npm install
        working-directory: ./frontend

      - name: Run tests with coverage
        run: npm run coverage
        working-directory: ./frontend

      - name: Upload coverage report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage
