name: Run Vitest Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js (with cache)
        if: env.ACT != 'true'
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'
          cache-dependency-path: ./frontend/package-lock.json
      
      - name: Set up Node.js (without cache, for act)
        if: env.ACT == 'true'
        uses: actions/setup-node@v4
        with:
          node-version: 18
      
          

      - name: Install dependencies
        run: npm install
        working-directory: ./frontend

      - name: Run tests with coverage
        run: npm run test -- --coverage
        working-directory: ./frontend

      - name: Upload coverage report
        if: ${{ env.CI == 'true' }}
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: ./frontend/coverage